global:
  scrape_interval: 2s
  evaluation_interval: 2s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: node-exporter
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080

  - job_name: alertmanager
    static_configs:
      - targets:
          - alertmanager:9093

  - job_name: prestashop
    static_configs:
      - targets:
          - prestashop:80

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
